{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_md_disks, instance)"
   },
   {
    "name": "md",
    "query": "label_values(node_md_is_active{instance=~\"$instance\"}, device)"
   },
   {
    "name": "sensor",
    "query": "label_values(mqtt_battery, topic)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "content": "<style type=\"text/css\">\np.markdown-html.panel-text-content {\noverflow: hidden;\n}\np.markdown-html.panel-text-content iframe {\nheight:225px;\n}\n</style>\n<script type=\"text/javascript\">\nvar weatherProperties = 'lat=52.366700&lon=4.894500&color=#FFFFFF&text-color=#FFFFFF&name=Amsterdam&units=uk';\n\n// initial load\ndocument.getElementById('embedweather').src = 'https://forecast.io/embed/?ts=' + (Date.now()) + '#' + weatherProperties;\n\n// refresh\nvar weatherRefresh = setInterval(function() { document.getElementById('embedweather').src = 'http://forecast.io/embed/?ts=' + (Date.now()) + '#' + weatherProperties; }, 1800000);\n\n</script>\n<iframe id=\"embedweather\" height=\"100%\" src=\"#\" style=\"margin: 0; padding: 0; border: none; width:100%; position:relative; top:-50px; overflow:hidden; margin-bottom: -70px;\"></iframe>\n"
  },
  {
   "title": "Temperature Garden",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "mqtt_temperature{job=\"mqtt\",topic=\"zigbee2mqtt_temp_sensor_garden\"}"
    }
   ]
  },
  {
   "title": "Temperature Bedroom",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "mqtt_temperature{job=\"mqtt\",topic=\"zigbee2mqtt_temp_sensor_bedroom\"}"
    }
   ]
  },
  {
   "title": "RPI Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    { "expr": "rpi_temperature" }
   ]
  },
  {
   "title": "Humidity Garden",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "mqtt_humidity{job=\"mqtt\",topic=\"zigbee2mqtt_temp_sensor_garden\"}"
    }
   ]
  },
  {
   "title": "Humidity Bedroom",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "mqtt_humidity{job=\"mqtt\",topic=\"zigbee2mqtt_temp_sensor_bedroom\"}"
    }
   ]
  },
  {
   "title": "Disks status in $md",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_md_disks_active{instance=~\"$instance\",device=\"$md\"}) / sum(node_md_disks{instance=~\"$instance\",device=\"$md\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(mqtt_battery, \"topic_short\", \"$1\", \"topic\", \"^zigbee2mqtt_(.*)\")",
     "legendFormat": "{{ topic_short }}"
    }
   ]
  },
  {
   "title": "Temperature Garden",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_temperature{job=\"mqtt\",topic=\"zigbee2mqtt_temp_sensor_garden\"}"
    }
   ]
  },
  {
   "title": "Humidity Garden",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_humidity{job=\"mqtt\",topic=\"zigbee2mqtt_temp_sensor_garden\"}"
    }
   ]
  },
  {
   "title": "Temperature Bedroom",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_temperature{job=\"mqtt\",topic=\"zigbee2mqtt_temp_sensor_bedroom\"}"
    }
   ]
  },
  {
   "title": "Humidity Bedroom",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_humidity{job=\"mqtt\",topic=\"zigbee2mqtt_temp_sensor_bedroom\"}"
    }
   ]
  }
 ]
}