{
 "title": "mdadm",
 "description": "Prometheus node_exporter mdadm module dashboard. Per Server and per md view",
 "tags": [
  "node",
  "disk",
  "mdstat"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_md_disks, instance)"
   },
   {
    "name": "host",
    "query": "label_values(node_md_disks{instance=~\"$instance\"}, instance)"
   },
   {
    "name": "md",
    "query": "label_values(node_md_state{instance=~\"$instance\"}, device)"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All mds are active",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_md_state{instance=~\"$instance\", device=\"$md\", state=\"active\"}) - sum(node_md_state{instance=~\"$instance\",device=\"$md\"})"
    }
   ]
  },
  {
   "title": "All md disks are active",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_md_disks{instance=~\"$instance\"}) - sum(node_md_disks{instance=~\"$instance\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "Total Active Disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_md_disks{instance=~\"$instance\", state=\"active\"})"
    }
   ]
  },
  {
   "title": "Total installed Disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_md_disks{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total MD RAIDs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_md_state{instance=~\"$instance\",device=\"$md\"})"
    }
   ]
  },
  { "title": "$instance $md RAID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "instance" },
  {
   "title": "$md is active",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_md_state{instance=~\"$instance\",device=\"$md\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "Disks status in $md",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_md_disks_required{instance=~\"$instance\",device=\"$md\"}) / sum(node_md_disks{instance=~\"$instance\",device=\"$md\", state=\"active\"})"
    }
   ]
  },
  {
   "title": "Disks active in RAID $host $md",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_md_disks{instance=~\"$instance\",device=\"$md\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "Disks configured in RAID $host $md",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_md_disks{instance=~\"$instance\",device=\"$md\"})"
    }
   ]
  },
  {
   "title": "Sync ratio $host $md",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_md_blocks_synced{instance=~\"$instance\",device=\"$md\"} / node_md_blocks{instance=~\"$instance\",device=\"$md\"}) * 100",
     "legendFormat": "{{device }}"
    }
   ]
  },
  { "title": "$instance $md RAID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$md is active",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_md_state{instance=~\"$instance\",device=\"$md\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "Disks status in $md",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_md_disks_required{instance=~\"$instance\",device=\"$md\"}) / sum(node_md_disks{instance=~\"$instance\",device=\"$md\", state=\"active\"})"
    }
   ]
  },
  {
   "title": "Disks active in RAID $host $md",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_md_disks{instance=~\"$instance\",device=\"$md\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "Disks configured in RAID $host $md",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_md_disks{instance=~\"$instance\",device=\"$md\"})"
    }
   ]
  },
  {
   "title": "Sync ratio $host $md",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_md_blocks_synced{instance=~\"$instance\",device=\"$md\"} / node_md_blocks{instance=~\"$instance\",device=\"$md\"}) * 100",
     "legendFormat": "{{device }}"
    }
   ]
  }
 ]
}