---

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Set timezone to {{ my_timezone }}
  timezone:
    name: "{{ my_timezone }}"

- name: Install all basic packages
  package:
    name: "{{ common_packages }}"
    state: present
  when: common_packages is defined

- name: Install python3 modules
  pip:
    executable: pip3
    name: "{{ pip_packages }}"
  when: pip_packages is defined

- name: check if raids exist
  stat:
    path: /etc/mdadm/mdadm.conf
  register: mdadm_conf

- name: add raid telegram alert
  lineinfile:
    dest: /etc/mdadm/mdadm.conf
    state: present
    regex: '^PROGRAM'
    line: "PROGRAM /usr/local/bin/teleSend"
  when: mdadm_conf.stat.exists == true
